Add class PromMetrics to stream Historical data from a Prometheus host
AICoE/prometheus-flatliner pull request #38
Opened 2018-12-07 21:41 UTC by 4n4nd

Rename old class PromMetrics to PromMetricsLive.
Change env variable names to "FLT_...".
Change default timeframe values

2018-12-10 12:13 UTC, durandom requested changes
some minor stuff. but other than that great.
also, would you mind squashing all those commits into one?

2018-12-10 12:13 UTC, durandom commented on metrics/prommetricslive.py
> +import json
well, stickler is right in that case. `json` is not used here

2018-12-10 12:13 UTC, durandom commented on metrics/prommetricslive.py
> +        print("Polling Prometheus for new metric data")
we need some sort of real logging.

2018-12-10 12:13 UTC, durandom commented on prometheus/prometheus.py
> +        return ((data))
why do you return a `(())` ? is that a list of lists?

2018-12-10 12:13 UTC, durandom commented on app.py
> +    weirdness_score.subscribe(print)
lets not add new `print` subscribers. this makes it only more noisy. please remove this

2018-12-11 13:38 UTC, 4n4nd commented
Let me just close this PR and create a new one with the fixes

2018-12-11 13:38 UTC, closed without merging