Fix potential Memory Bloats in AlertFrequencyVersion Flatliner
AICoE/prometheus-flatliner pull request #91
Opened 2019-03-29 19:44 UTC by 4n4nd

Previous commit was AlertFrequencyCluster fix

2019-03-29 20:27 UTC, durandom requested changes
could you please add an example entry for each dict?

2019-03-29 20:27 UTC, durandom commented on flatliners/baseflatliner.py
> +        if not ttl:
But isn't `ttl` defaulted to 900?
So if you dont provide it as an argument, it'll still return a LRUCache.
You have to explictly pass `None`, which feels awkward

2019-03-29 20:27 UTC, durandom commented on flatliners/alertfrequencyversion.py
> +        # for a specific version should not expire based on time, so ttl=None
but some versions will go away soon, especially the shorter-lived versions coming from the CI.

2019-03-29 20:38 UTC, durandom commented
a general question: does TTLCache update the expire time every time an item is accessed?
I other words, if I access `a[1]` every second and the TTL is set to 2, then `a[1]` will never be removed from the cache, right?
Or will every item expire after ttl?
Could you try that? I didnt find anything in the source code

2019-03-29 20:43 UTC, durandom commented
So, reading the documentation again, I think we want to use `LRUCaches` everywhere.
The TTLCache seems to discard items after TTL no matter what, which is not what we want.

2019-03-30 15:59 UTC, 4n4nd commented
ttl will only reset when the values are modified, so yes I think we should use LRUcaches everywhere. which will make everything simpler too

2019-04-01 12:50 UTC, durandom requested changes
yes, agreed. 

there are still some ttl references in this PR though

2019-04-01 12:54 UTC, 4n4nd commented
Oops I forgot to label it as WIP

2019-04-01 13:57 UTC, durandom approved these changes

2019-04-01 13:57 UTC, merged